sudo: required
script:
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Travis-CI"
  - git submodule update --init --recursive
  - deps/reflex-platform/work-on ghcjs ./. --command "cabal configure --ghcjs && cabal build" # ./try-reflex --command "exit 0"
  # - travis_wait ./test -j 2
cache:
  directories:
    - /nix
os:
  - linux
  # - osx  # TODO
