sudo: required

before_install:
 - openssl aes-256-cbc -K $encrypted_3c89d919c82e_key -iv $encrypted_3c89d919c82e_iv -in deploy_key.enc -out deploy_key -d

script:
- git config --global user.email "travis-ci@example.com"
- git config --global user.name "Travis-CI"
- git submodule update --init --recursive
- cd deps/reflex-platform
- ./try-reflex
- cd ../..
- cabal configure --enable-tests && cabal build
- bash ./deploy

# - deps/reflex-platform/work-on ghc ./. --command "cabal configure --enable-tests && cabal build"
# - bash ./deploy.sh

cache:
  directories:
  - /nix
os:
- linux

env:
  global:
    - ENCRYPTION_LABEL: "3c89d919c82e"
    - COMMIT_AUTHOR_EMAIL: "imalsogreg@gmail.com"
